export const STORAGE_KEYS = {
  SESSION: 'chromeDiffPair.activeSession',
  URL_ASSIST: 'chromeDiffPair.urlAssist',
};

export const SIDE = {
  LEFT: 'left',
  RIGHT: 'right',
};

export const MESSAGE_TYPES = {
  START_SESSION: 'START_SESSION',
  RESUME_SESSION: 'RESUME_SESSION',
  END_SESSION: 'END_SESSION',
  TOGGLE_SCROLL_SYNC: 'TOGGLE_SCROLL_SYNC',
  TOGGLE_URL_SYNC: 'TOGGLE_URL_SYNC',
  PAGE_SCROLL: 'PAGE_SCROLL',
  PAGE_NAVIGATED: 'PAGE_NAVIGATED',
  REALIGN_REQUEST: 'REALIGN_REQUEST',
  SESSION_STATE_UPDATED: 'SESSION_STATE_UPDATED',
  WINDOW_CLOSED: 'WINDOW_CLOSED',
  REOPEN_MISSING_SIDE: 'REOPEN_MISSING_SIDE',
  GET_SESSION_STATE: 'GET_SESSION_STATE',
  CONTROL_PAUSE_SYNC: 'CONTROL_PAUSE_SYNC',
};

export const SUPPRESSION_MS = 1200;
export const SCROLL_BROADCAST_THROTTLE_MS = 40;
